[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_litesvm_example = "4RLEF64sgjkSzpY6hTBHbpBJg9qbv4mbQfArJDKJwEvU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
